apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "kubernetes-ssh-container-exposer.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "kubernetes-ssh-container-exposer.fullname" . }}-clusterrole
subjects:
- kind: ServiceAccount
  name: {{ template "kubernetes-ssh-container-exposer.fullname" . }}-serviceaccount
  namespace: {{ .Release.Namespace }}