apiVersion: v1
kind: Pod
metadata:
  name: {{ template "kubernetes-ssh-container-exposer.fullname" . }}-sshpiper
  labels:
    app: {{ template "kubernetes-ssh-container-exposer.name" . }}-sshpiper
    chart: {{ template "kubernetes-ssh-container-exposer.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  containers:
    - name: {{ template "kubernetes-ssh-container-exposer.name" . }}-sshpiper
      image: "{{ .Values.sshpiper.image.repository }}:{{ .Values.sshpiper.image.tag }}"
      imagePullPolicy: {{ .Values.sshpiper.image.pullPolicy }}
      ports:
        - containerPort: 2222
      env:
        - name: SSHPIPERD_UPSTREAM_DRIVER
          value: mysql
        - name: SSHPIPERD_UPSTREAM_MYSQL_HOST
          value: "$({{ template "mysql.host" . }})"
        - name: SSHPIPERD_UPSTREAM_MYSQL_PASSWORD
          value: {{ .Values.mysql.mysqlRootPassword }}
        - name: SSH_HOST_RSA_KEY
          value: "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBeEJ1ZU80aDFhSmtnQ3AxWm1WdmxUbU5aMFZtdUUrZHJ2aUZsbmhzV1ZVSzdLeVpMCnVnUXdTQzJxUm1JRjVGN0J5bFpHaTJ2YkwzbjVoenRGNUlVQVJZTmVzRVpxVnFnVFBWT2l0NXlrc3Uzc21iOW0KK2VhYTVOZktQblhaL3RWSDJmd2FESVNNVFZpSHJOaHc3VVdXV1h1eVZ5Qlk2UmtRTzkxZEdxZHJYU3JWSEo5dwpFNlJYbENHV0xoUnNwWHd5aU1WNU5PMDNucTJwOXBFL2t6VE5CU1JtVzNUdjhtZytLc2tKWVkyQ0pBYWYxVmZKCnIvME5jWkZ5c1ZkUTA1N1lONzlGVlk5WUJOdjAzR0pCaDZHYnN4RWNRL0ZpZCtCZFMycFMyVm5XM1FlSGFPVmEKWW1FQ0g3Q1JzeEk3d05wTk1yMVdKcnl6T0J0YTdVMTN2ZHJtQ1FJREFRQUJBb0lCQUNpTHhVVnR5MGliRUVMaAprWnJob3lGMzdTUVp0S0lzNE52b3I4Zm10ZEZmQUsvRk5UYjZrcmo1cUJEeFIyS1dMTjhXdzNNa0U2ZFhRcjR4CkJSeGdXMVFEKzFuYTFUV2hmb2paZC9VYWovcm1zbHAvZGwwSXp0R3R4QVR4L09aeFZtKzliZTFVb21XRGZsbkEKVG1qZ1VGdWo5WldKL0pnRk5KUU1DcW51SDRhZGJkVXhjUjhiVCtBWlVPTmFUWjdwYXZmdlJ4dlpyWEZJSkVrawpYNXNzVGFLTkRRa2QzZE9Sd0NObUIrMGJEcVNZT3FtQUMyc2dHVWY5azIyTHZ1aVIzYmN0Tkg4Z1RWZit5YlFkCjVnc0VuQWxMRnhyR3dZcTVzQWxWakxGclZ0U3VhV0hLLzVaSW9sSWhaSnpoNXpTeCtNcXVLM1U1TmRza2lpM0MKc0QzbW9XRUNnWUVBM1BlR1JqOEVOaUVOYVZmUmd0L0lxanFQQ0tMSDgweDhqU20rNjZOcm1ic2xWODMxbUVNUAozVXZsT1ZZVWs0R0ViQUNsd1pHRTJZb1hIV28zU1J0SzRjY2N4bFF6SG9rMCt1REphQnRmeEpLaG9tTFB1YlJFCmNnZjBLOWcvQ0JkYWZGeXB0ZmtBdXVFVlZ4NVQxYXZRYzhvcGtUR0I1aHBPUy9Ua3AzZ21MdlVDZ1lFQTR6TWgKYnIzb2J6bGxHQlJ2UVdtc1BmUjNYOFhJdmd5aXZqdzliOTU3VHVUN1A0N1hOd0svTXhjVER0TFp0UEV6U0JiWQpaNmhjRlJHMDFqaGR6VGlzSEtqaGRDZUwraVhwMDFrelVMdlNkeE9henlDSit2VlpseGhIck5MdC9TS2JJYVBTCnVPZTZiSm0ydVJWUjFvV2VVZTcydW0xV3RHWFFTSG1WVTAyTWhrVUNnWUVBbmM1WW9zcFdZNkh2UmhCbG5DWGQKMVZURTJkSUhJb2E1WE1jM2htbkxhcHJ3N0dnMndXc0RaWFBTWE1SUkpaY1Z6MXdYQk1xOEtmQW8yZVVGWHJ5VApHZk50WldhMHExWXA5QkdkUlRCbmtLZDNyOVVKclFKRTczc21zamxacXBtakViWExyaDRLbTJ3c0pXK1BSOFhRCnRTRG4xcjJZbTVDbDRqRWZLMHJ2V2hFQ2dZRUF0U2FwZTREVCtRck1QanpjMEUwUFZuNjdSNU9Oa1dyRnYrU00KSDh4R2lRc3VBT2xGVThsTzVjOTZGSkd0b0FYSkc2dUxkR3Jhc0xuamRBS1JWL1hkMVNRYVR1RFJUT3c1MlpmLwp3RmxoWUN3emZQNjJ4WEFtdE1CWk5jVWdtSHFsTWxkS3hyK005dFpBeUtYbEVLU05MVXJaVXArblNFTDlwU3U4CkVpVjg2L2tDZ1lBTEVScmljNk5hSC9rb0tSWVpBTkxRaHhDM0p1MHY5QnZPVzVtakhnM0diS0tkYW1RTkxGQjYKNXdxMTFUa20zbGRHRW16bVVpOFZhRFE2UktrT3lnYjdDbFN4UnAwY3c2MFNLbWtEQjhrbndaSUNkY1lQMUJRbQpkaGMxR1Q0UW5jWmhDa1Vza3dkRzFBTWF2YjZMa2c1eVBhTW83SXZhSkRMSjh1SWpiRXlhR0E9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQ"
  imagePullSecrets:
  - name: dockerhub
  hostNetwork: true