apiVersion: v1
kind: Service
metadata:
  labels:
    app: ssh-example
  name: ssh-example
spec:
  clusterIP: 172.30.0.5
  ports:
    - name: ssh
      port: 22
      protocol: TCP
      targetPort: 22
  selector:
    app: ssh-example
  type: ClusterIP
status:
  loadBalancer: {}